services:
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - frontend_network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}  
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - backend_network
      - frontend_network
    command: ["wait-for-it", "db:3306", "--", "flask", "run", "--host=0.0.0.0", "--port=5000"]


  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}  
      - MYSQL_DATABASE=${DB_NAME} 
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend_network

volumes:
  db_data:

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge