 apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: omersade/backend-movie:v2
        env:
        - name: DB_PASSWORD
          value: "3502"
        - name: DB_NAME
          value: "todo_db"
        - name: DB_HOST
          value: "db"
        - name: DB_PORT
          value: "3306"
        ports:
        - containerPort: 5000
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "3502"
        - name: MYSQL_DATABASE
          value: "todo_db"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: db-init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: db-init-script
        configMap:
          name: db-init-script

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000  
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP

