apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.image.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        ports:
        - containerPort: {{ .Values.backend.image.containerPort }}
        envFrom:
            - secretRef:
                name: db-credentials
        resources:
          requests:
            cpu: {{ .Values.backend.image.resources.requests.cpu }}
            memory: {{ .Values.backend.image.resources.requests.memory }}
          limits:
            cpu: {{ .Values.backend.image.resources.limits.cpu }}
            memory: {{ .Values.backend.image.resources.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: {{ .Values.backend.image.containerPort }}
  type: ClusterIP
