apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
  labels:
    app: backend
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS todo_db;
    USE todo_db;

    CREATE TABLE IF NOT EXISTS movie (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        poster VARCHAR(255) NOT NULL
    );