apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-db-secret
spec:
  secretStoreRef:
    name: my-aws-secret-store  
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: mysql/secrets
        property: DB_PASSWORD
    - secretKey: DB_NAME
      remoteRef:
        key: mysql/secrets
        property: DB_NAME
    - secretKey: DB_HOST
      remoteRef:
        key: mysql/secrets
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: mysql/secrets
        property: DB_PORT
  refreshInterval: 1h