apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
annotations:
  nginx.ingress.kubernetes.io/proxy-connect-timeout: "90"
  nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
  nginx.ingress.kubernetes.io/proxy-send-timeout: "90"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.frontend.ingress.host }}
    http:
      paths:
      - path: {{ .Values.frontend.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
annotations:
  nginx.ingress.kubernetes.io/proxy-connect-timeout: "90"
  nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
  nginx.ingress.kubernetes.io/proxy-send-timeout: "90"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.backend.ingress.host }}
    http:
      paths:
      - path: {{ .Values.backend.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5000

