---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.backend.dbSecret.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: {{ .Release.Namespace }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: db-credentials
    template:
      type: Opaque
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.backend.dbSecret.path }}
        property: DB_PASSWORD
    - secretKey: DB_NAME
      remoteRef:
        key: {{ .Values.backend.dbSecret.path }}
        property: DB_NAME
    - secretKey: DB_HOST
      remoteRef:
        key: {{ .Values.backend.dbSecret.path }}
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: {{ .Values.backend.dbSecret.path }}
        property: DB_PORT
