apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  labels:
    release: my-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: "5000"
      path: "/metrics" 
      scheme: https           
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitor
  labels:
    release: my-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: frontend
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: "80"
      path: "/metrics"         
      scheme: https           
      interval: 30s

