name: Commit and Push Changes

on:
  push:
    branches:
      - main

jobs:
  push_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Make changes
        run: echo "New change" >> VERSION.txt

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Increment version to v1"
          git push 



